package modelo;
// Generated 18/05/2017 09:53:17 PM by Hibernate Tools 4.3.1



/**
 * Biblioteca generated by hbm2java
 */
public class Biblioteca  implements java.io.Serializable {


     private int idBiblio;
     private String nombreBiblio;
     private String institucion;

    public Biblioteca() {
    }

    public Biblioteca(int idBiblio, String nombreBiblio, String institucion) {
       this.idBiblio = idBiblio;
       this.nombreBiblio = nombreBiblio;
       this.institucion = institucion;
    }
   
    public int getIdBiblio() {
        return this.idBiblio;
    }
    
    public void setIdBiblio(int idBiblio) {
        this.idBiblio = idBiblio;
    }
    public String getNombreBiblio() {
        return this.nombreBiblio;
    }
    
    public void setNombreBiblio(String nombreBiblio) {
        this.nombreBiblio = nombreBiblio;
    }
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }




}


