package modelo;
// Generated 18/05/2017 09:53:17 PM by Hibernate Tools 4.3.1



/**
 * Tesis generated by hbm2java
 */
public class Tesis  implements java.io.Serializable {


     private String numAdquisicion;
     private String titulo;
     private String autor;
     private String carrera;

    public Tesis() {
    }

    public Tesis(String numAdquisicion, String titulo, String autor, String carrera) {
       this.numAdquisicion = numAdquisicion;
       this.titulo = titulo;
       this.autor = autor;
       this.carrera = carrera;
    }
   
    public String getNumAdquisicion() {
        return this.numAdquisicion;
    }
    
    public void setNumAdquisicion(String numAdquisicion) {
        this.numAdquisicion = numAdquisicion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }




}


